insert into music_in_album(music_id, album_id) values (1, 3);
insert into music_in_album(music_id, album_id) values (2, 2);
insert into music_in_album(music_id, album_id) values (3, 2);
insert into music_in_album(music_id, album_id) values (4, 2);
insert into music_in_album(music_id, album_id) values (5, 2);
insert into music_in_album(music_id, album_id) values (6, 4);
insert into music_in_album(music_id, album_id) values (7, 1);
insert into music_in_album(music_id, album_id) values (8, 1);
insert into music_in_album(music_id, album_id) values (9, 1);